### ISSUE TITLE
datetime parsing fails after Home Assistant Core 2024.10.2 update

### ISSUE THREAD

**Issue by tk-314** [saaste/fmi-weather-client#60]
After Home Assistant Core update to 2024.10.2 fmi_weather_client starts to fail:
`2024-10-14 07:15:47.136 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fmi/__init__.py", line 365, in _async_update_data
    self.current = await fmi.async_weather_by_coordinates(self.latitude, self.longitude)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fmi_weather_client/__init__.py", line 37, in async_weather_by_coordinates
    return await loop.run_in_executor(None, weather_by_coordinates, lat, lon)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fmi_weather_client/__init__.py", line 19, in weather_by_coordinates
    forecast = forecast_parser.parse_forecast(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fmi_weather_client/parsers/forecast.py", line 26, in parse_forecast
    times = _get_datetimes(data)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fmi_weather_client/parsers/forecast.py", line 73, in _get_datetimes
    timestamp = datetime.utcfromtimestamp(int(parts[2])).replace(tzinfo=timezone.utc)
                                              ~~~~~^^^
IndexError: list index out of range`

It looks like date.utcfromtimestamp() is deprecated and should be replaced with datetime.fromtimestamp()?

**Comment by fursov** [comment]
I think, this is duplicate to my report #58.

I also provided the fix in #59 but @saaste did not respond to this ticket yet.

And, yes, utcfromtimestamp is deprecated but this is not [yet] the root cause of the crash.
